default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: areyousmarterAPI_development

test:
  <<: *default
  database: areyousmarterAPI_test

production:
  <<: *default
  database: areyousmarterAPI_production
  username: areyousmarterAPI
  password: <%= ENV['AREYOUSMARTERAPI_DATABASE_PASSWORD'] %>
